name: Weather 

on:
  schedule:
    # UTC 时间每天 8 点运行，对应北京时间 16 点
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: Send weather forecast

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      USER_ID: ${{ secrets.USER_ID }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      CITY: ${{ secrets.CITY }}
